version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
    # runtime-versions:
    #   nodejs: 12

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Build Phase
      - npm run build
